pc:
  name: HJT_PC
  mac_address: 9C-6B-00-1D-33-BB
api:
  host: 0.0.0.0
  port: 8420
scripts:
- id: shutdown
  name: PC Herunterfahren
  icon: power_off
  command: shutdown /s /t 0
  confirm: true
  timeout: 10
  group: jkkl
  order: 0
- id: restart
  name: PC Neustarten
  icon: restart_alt
  command: shutdown /r /t 0
  confirm: true
  timeout: 10
  group: jkkl
  order: 1
- id: steam
  name: Steam starten
  icon: games
  command: start steam://open/main
  confirm: false
  timeout: 5
  group: jkkl
  order: 2
- id: lock
  name: PC Sperren
  icon: lock
  command: rundll32.exe user32.dll,LockWorkStation
  confirm: false
  timeout: 5
  group: Ih
  order: 3
- id: tv_mode
  name: TV-Modus
  icon: tv
  command: C:\Users\hanne\Documents\PC-Connector\TV.bat
  confirm: false
  timeout: 10
  group: jkkl
  order: 4
- id: desk_mode
  name: Schreibtisch-Modus
  icon: desktop_windows
  command: C:\Users\hanne\Documents\PC-Connector\Schreibtisch.bat
  confirm: false
  timeout: 5
  group: jkkl
  order: 5
- id: g
  name: g
  icon: play_arrow
  command: fh
  confirm: false
  timeout: 30
  group: ''
  order: 6
category_order:
- Ih
- jkkl
