const ICONS: Record<string, string> = {
  play_arrow: "▶️",
  power_settings_new: "⏻",
  restart_alt: "🔄",
  refresh: "🔄",
  lock: "🔒",
  logout: "🚪",
  login: "🔑",
  volume_up: "🔊",
  volume_off: "🔇",
  computer: "🖥️",
  desktop_windows: "🖥️",
  monitor: "🖥️",
  terminal: "💻",
  code: "💻",
  folder: "📁",
  folder_open: "📂",
  description: "📄",
  insert_drive_file: "📄",
  download: "⬇️",
  upload: "⬆️",
  content_paste: "📋",
  content_copy: "📋",
  mouse: "🖱️",
  keyboard: "⌨️",
  gamepad: "🎮",
  sports_esports: "🎮",
  music_note: "🎵",
  movie: "🎬",
  photo: "🖼️",
  image: "🖼️",
  wifi: "📶",
  bolt: "⚡",
  flash_on: "⚡",
  rocket_launch: "🚀",
  settings: "⚙️",
  build: "🔧",
  bug_report: "🐞",
  star: "⭐",
  favorite: "❤️",
  home: "🏠",
  work: "💼",
  shopping_cart: "🛒",
  timer: "⏱️",
  schedule: "🕒",
  brightness_high: "☀️",
  dark_mode: "🌙",
  cloud: "☁️",
  link: "🔗",
  send: "📨",
  history: "📜",
  chrome_reader_mode: "🌐",
  language: "🌐",
  public: "🌐",
};

export function iconFor(name?: string): string {
  if (!name) return "▶️";
  return ICONS[name] ?? "▶️";
}
